name: contacts
description: A set of classes useful for managing contacts.
version: 2.0.0
repository: https://github.com/Marco87Developer/contacts
# homepage: https://marco87.dev

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  collection: ^1.17.0
  geos: ^2.1.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

assets:
  - test/models/address/address_not_valid_1_test.json
  - test/models/address/address_not_valid_2_test.json
  - test/models/address/address_test.json
  - test/models/chat/chat_not_valid_1_test.json
  - test/models/chat/chat_not_valid_2_test.json
  - test/models/chat/chat_test.json
