name: contacts
description: A set of classes useful for managing contacts, for save in a database and retrieve from it.
version: 1.0.0
repository: https://github.com/Marco87Developer/contacts
homepage: https://marco87.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.0.2-dev.2
  pedantic: ^1.11.0
  url_launcher: ^6.0.2

flutter:
