name: contacts
description: A set of classes useful for managing contacts, for save in a database and retrieve from it.
version: 1.1.0
repository: https://github.com/Marco87Developer/contacts
homepage: https://marco87.dev

environment:
  sdk: ">=2.13.3 <3.0.0"
  flutter: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # mocktail: ^0.0.2-dev.2
  lints: ^1.0.1

flutter:
